### ISSUE TITLE
Publishing to a beamer presentation does not work

### ISSUE THREAD

**Issue by rich-iannone** [rstudio/gt#109]
Currently, we cannot include a **gt** table inside of a beamer presentation. Doing so results in an error code that is uninformative.

Issue originally discovered and suggested by @tareefk .

**Comment by emmadehaan** [comment]
I have a solution for the beamer output with rmarkdown whenever you obtain the following error:
```
! Undefined control sequence.
\beamer@doifinframe ...meslide}\par \captionsetup 
                                                  [table]{labelformat=empty,...
l.110 \end{frame}
```

This was the case for me when I would add the gt package and output a table within an r-block with gt().

What solved the issue was to add the following code at the preamble:
```
header-includes:
- \usepackage{booktabs}
- \usepackage{caption}
- \usepackage{longtable}
- \makeatletter
- \let\@@magyar@captionfix\relax
- \makeatother
```

thus, to clarify with an example:
```rmarkdown
---
title: "Test"
author: "Author"
date: "12/16/2019"
output: beamer_presentation
header-includes:
- \usepackage{booktabs}
- \usepackage{caption}
- \usepackage{longtable}
- \makeatletter
- \let\@@magyar@captionfix\relax
- \makeatother
---

```{r test,echo = FALSE, message=FALSE, warning = FALSE}
library(tidyverse)
library(gt)
datasets::mtcars %>% 
 head() %>% select(mpg, cyl) %>%
 gt::gt() %>% 
 gt::fmt_number(everything())
``` ## 

```

Solution and reasoning for the pre-amble found in this [discussion](https://tex.stackexchange.com/questions/426088/texlive-pretest-2018-beamer-and-subfig-collide)

**Comment by setgree** [comment]
Hi there, it looks like this was an Rstudio-internal discussion, and thus it's missing a bit of the context (and the reproducible examples) that I would normally look to for debugging. is it possible to get a bit more explanation of the issue and why it occurred? I am having a hell of a time getting my gt(0 tables to knit in a beamer document and I swear it was working as recently as two days ago. Thanks!
