### ISSUE TITLE
tab_spanner() does nothing if columns start with a number

### ISSUE THREAD

**Issue by sharlagelfand** [rstudio/gt#127]
It looks like tab_spanner() is not able to handle columns that start with numbers! (not ideal in general, I know, but I have them)

the gt_tbl output is nonsense HTML so I've excluded it -- but this was created using reprex :)

``` r
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
library(gt)

df <- tibble(`1_x` = c(1, 2),
             `2_x` = c(1, 2), 
             x_1 = c(3, 4),
             x_2 = c(3, 4))

# Tab spanner works if variables start with a character
df %>%
  gt() %>%
  tab_spanner(label = "x",
              columns = vars(x_1, x_2))

# select_at() works if variables start with a number

df %>%
  select_at(vars(`1_x`, `2_x`))

#> # A tibble: 2 x 2
#>   `1_x` `2_x`
#>   <dbl> <dbl>
#> 1     1     1
#> 2     2     2

# Nothing happens when using tab spanner on variables starting with a number

df %>%
  gt() %>%
  tab_spanner(label = "x",
              columns = vars(`1_x`, `2_x`))
```

**Comment by rich-iannone** [comment]
Thanks for reporting this! It's interesting that the `select_at()` example works fine with variables starting with a number (and that the gt analogue does not). The last `tab_spanner()` does work with some unintuitive changes:

```
# this works!
df %>%
  gt() %>%
  tab_spanner(
    label = "x",
    columns = vars("1_x", "2_x")
  )

# this too!
df %>%
  gt() %>%
  tab_spanner(
    label = "x",
    columns = c("1_x", "2_x")
  )
```

But it's pretty odd that it doesn't work like dplyr's vars with the back ticks which is the standard way to do it. I'll look into a fix for this. But, for now, at least there is a workaround (that should work even when the fix is implemented).
