### ISSUE TITLE
Have numbers formatted with suffixes like K, M, B, T

### ISSUE THREAD

**Issue by jkfding** [rstudio/gt#134]
Really, really love this package! It is amazing. :)

What would make it even better is having an option (maybe in fmt_number) to automatically add endings to numbers like K (thousands), M (millions), B (billions), and T (trillions) for large numbers.

Example: 
the numbers 1, 1000, 2432000, 234202034, 20340000000000 get formatted as

1.00, 1.00K, 2.43M, 234.20M, 20.34T

**Comment by rich-iannone** [comment]
This is a great idea, and something we thought about awhile back. In reading up about this, I think that the sequence is generally: k or K or M (thousands, not always used), M or MM (millions), B (billions), and less commonly T (trillions).

Since these are so various, we could have the user choose (but have defaults of `c("K", "M", "B", "T")`) by specifying a character vector of four elements for the symbols. If we don't want to use `K` for instance, and start this formatting at `M`, we can put in an NA (`c(NA, "M", "B", "T")`). A single argument in `fmt_number()` (`suffixing`) could handle this. Here are some examples with a column containing `1`, `1000`, `20E+6`, `25E+9`, `30E+12`:

```
# default case where suffixing is TRUE 
data %>%
  fmt_number(
   decimals = 2,
    suffixing = TRUE)
-> "1.00", "1.00K", "20.00M", "25.00B", "30.00T"
```

```
# case where suffixing is c(NA, "Mio", "Bn", "T") 
data %>%
  fmt_number(
   decimals = 2,
    suffixing = c(NA, "Mio", "Bn", "T"))
-> "1.00", "1000.00", "20.00Mio", "25.00Bn", "30.00T"
```

**Comment by rich-iannone** [comment]
Just thinking about this a bit more and it seems kinda reasonable to have this work in `fmt_currency()` as well. Don't know why I didn't think of that earlier, but I thought of it just now, and that's what really matters.

**Comment by r-cheologist** [comment]
I commented [here](https://github.com/rstudio/gt/pull/135#issuecomment-454708974), but PLEASE also implement easy scientific notation, e.g. `1500000` --> "1.5 <&#215; OR &#183; e.g.> 10^6^.

**Comment by rich-iannone** [comment]
@r-cheologist scientific notation formatting is already implemented in `fmt_scientific()` (https://gt.rstudio.com/reference/fmt_scientific.html).

**Comment by jkfding** [comment]
I tried out the new feature. Works wonderfully! Thanks so much. 

BTW new r user here and even though I've got little experience with it, packages like gt make it so easy for the beginner. People here at work like the package a lot. There's nothing else quite like this package, it's just so useful. THANKS!!
