### ISSUE TITLE
Ability to add data.row.padding to certain rows only

### ISSUE THREAD

**Issue by JacobHerbstman** [rstudio/gt#1418]
## Proposal

I have gotten requests from my boss to add spaces above certain rows to make the table more readable. It would be nice if for the tab_options(data.row.padding) function, I could write tab_options(data.row.padding = px(30), locations = cells_body(rows = c(5,6))) or something similar. 

Is there already a way to do this? If not, I think this would be a nice feature to try to implement.

**Comment by rich-iannone** [comment]
There is a way to do this, but it isn't very obvious. The key is to use `tab_style()` and the `css()` helper function. Here's an instructive example of how to modify the top and bottom padding in cells of rows 3 through to 5:

```r
library(gt)

exibble |>
  gt() |>
  tab_style(
    style = css(`padding-top` = px(30), `padding-bottom` = px(30)),
    locations = cells_body(rows = 3:5)
  )
```

<img width="1022" alt="data-row-padding-css" src="https://github.com/rstudio/gt/assets/5612024/fb518d7c-425d-4564-9421-f2c1ebcb46f0">

Note that every cell in a row must have the same padding applied (and this is the case since the default for `cells_body()`'s `columns` argument is `everything()`.

Hope this helps!

**Comment by JacobHerbstman** [comment]
thank you so much! This is perfect.
