### ISSUE TITLE
Render tables with HTML columns

### ISSUE THREAD

**Issue by TuSKan** [rstudio/gt#146]
Is possible to render HTML content on **gt** ? 

```r
data.frame(A = "Text", B = html("<em>Text</em>")) %>% gt()
```
<table style=\"font-family:-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;display:table;border-collapse:collapse;margin-left:auto;margin-right:auto;color:#000000;font-size:16px;background-color:#FFFFFF;width:auto;border-top-style:solid;border-top-width:2px;border-top-color:#A8A8A8;\"><tr><th style=\"color:#000000;background-color:#FFFFFF;font-size:16px;font-weight:initial;vertical-align:middle;padding:10px;margin:10px;text-align:center;\" rowspan='1' colspan='1'>A</th><th style=\"color:#000000;background-color:#FFFFFF;font-size:16px;font-weight:initial;vertical-align:middle;padding:10px;margin:10px;text-align:center;\" rowspan='1' colspan='1'>B</th></tr><tbody style=\"border-top-style:solid;border-top-width:2px;border-top-color:#A8A8A8;border-bottom-style:solid;border-bottom-width:2px;border-bottom-color:#A8A8A8;\"><tr><td style=\"padding:10px;margin:10px;vertical-align:middle;text-align:center;\">AAAA</td><td style=\"padding:10px;margin:10px;vertical-align:middle;text-align:center;\">&lt;em&gt;HTML&lt;/em&gt;</td></tr></tbody></table>

**Comment by jdbarillas** [comment]
I had the same question, the problem seems to be that the `<` and `>` signs get converted to their HTML entities `&lt;` and `&gt;`, respectively, when passed into gt. 

My solution was to create my own `html` function that replaced the entities with their signs before calling the HTML function.

```r
html <- function(text, replace_sign_entities = FALSE, ...) {
  
  if(replace_sign_entities) {
    text <- stringr::str_replace_all(text, c("&lt;" = "<", "&gt;" = ">"))
  }
  
  htmltools::HTML(text, ...)
}
```

and then use `text_transform` as seen in #126 to pass it as the function.  So with your example (adding `stringsAsFactors = FALSE`) it would look like 

```r
data.frame(A = "Text", B = "<em>Text</em>", stringsAsFactors = FALSE) %>% 
  gt() %>% 
  text_transform(
    locations = cells_data(vars(B)),
    fn = function(x){
      html(x, replace_sign_entities = TRUE)
    }
  ) 
```



<div id="eocluljobe" style="overflow-x:auto;">



<table class="gt_table">

<tr>

<th class="gt_col_heading gt_left" rowspan="1" colspan="1">

A

</th>

<th class="gt_col_heading gt_left" rowspan="1" colspan="1">

B

</th>

</tr>

<tbody class="gt_table_body">

<tr>

<td class="gt_row gt_left">

Text

</td>

<td class="gt_row gt_left">

<em>Text</em>

</td>

</tr>

</tbody>

</table>



</div>



Now, to make it work with multiple rows and columns, you'll have to add `map` to your function in `text_transform` since `html` returns one vector. There's probably a better way to do this but it would look something like this 

```r
data.frame(A = c("<b>Text</b>", "<del>Text</del>"), B = c("<em>Text</em>", "Text"), stringsAsFactors = FALSE) %>% 
  gt() %>% 
  text_transform(
    locations = cells_data(vars(A, B)), # More than one column, row
    fn = function(x){
      purrr::map(x, html, replace_sign_entities = TRUE) # use map here
    }
  ) 
```



<div id="sclsyxsife" style="overflow-x:auto;">



<table class="gt_table">

<tr>

<th class="gt_col_heading gt_left" rowspan="1" colspan="1">

A

</th>

<th class="gt_col_heading gt_left" rowspan="1" colspan="1">

B

</th>

</tr>

<tbody class="gt_table_body">

<tr>

<td class="gt_row gt_left">

<b>Text</b>

</td>

<td class="gt_row gt_left">

<em>Text</em>

</td>

</tr>

<tr>

<td class="gt_row gt_left gt_striped">

<del>Text</del>

</td>

<td class="gt_row gt_left gt_striped">

Text

</td>

</tr>

</tbody>

</table>



</div>



<sup>Created on 2019-01-29 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by rich-iannone** [comment]
This now works with `fit_markdown()`. Here's a working example:

```r
dplyr::tibble(A = "Text", B = "<em>Text</em>") %>%
  gt() %>%
  fmt_markdown(columns = vars(B))
```

**Comment by leungi** [comment]
@rich-iannone : can't express enough of my appreciation of your work with `gt` and `blastula`; match made in heaven 😁🙏

**Comment by rich-iannone** [comment]
@leungi Aww thanks! There's still TONS of work to be done. So, thanks for being patient with the development process (and the little problems along the way).

**Comment by leungi** [comment]
> @leungi Aww thanks! There's still TONS of work to be done. So, thanks for being patient with the development process (and the little problems along the way).

Without y'alls' hard work, it would've been a 🗻for me (with minimal HTML/CSS knowledge 😅) to do something like:

![image](https://user-images.githubusercontent.com/30273868/81724553-2ce64280-944a-11ea-80fa-88231eb70f93.png)

Kudos 🙌
