### ISSUE TITLE
Is opt_interactive() compatible with blastula/email packages?

### ISSUE THREAD

**Issue by danmika** [rstudio/gt#1476]
Hi all,

I'm building a tool to deliver local economic data updates to people at my university via email. gt tables without interactivity work well with the `blastula` package, but the tables I'm generating are 36 rows and there's four tables per email. The pagination options in `opt_interactive` render in Rstudio, but not in the viewer tab or in test emails. Here's my code:

```
gt_test_df <- gt(test_df) %>% 
  tab_header(
    title = "Header",
    subtitle = "Source subtitel"
  )
  
opt_test<- opt_interactive(
  gt_test_df,
  active = TRUE,
  use_pagination = TRUE,
  use_pagination_info = TRUE,
  use_sorting = FALSE,
  use_compact_mode = TRUE,
  use_page_size_select = TRUE,
  page_size_values = c(12, 24, 36)
)

blastula::email <- compose_email(
 body = "Test body",
opt_test,
 footer = "This tool is in beta"
)
```

Is it possible to render an interactive table like this in an email? Static tables work but take up a lot of space, and I'd like to save the end user the hassle of downloading an html file.

**Comment by rich-iannone** [comment]
Unfortunately, due to the limitations of email, interactive tables will not work when sent as part of a message. HTML email typically disallows any JavaScript and so you’re left with a non-functioning interactive table. And since interactive tables have a JavaScript component, they cannot be used. 

Some things you can do are condense the content of the static tables before inclusion into the email message body (e.g., less columns, narrrower columns, less vertical space per row). Or, you could link to an interactive table hosted on a webpage.
