### ISSUE TITLE
HTML export buttons

### ISSUE THREAD

**Issue by fmmattioni** [rstudio/gt#148]
Any chance of having HTML export buttons as in the following link?

https://datatables.net/extensions/buttons/examples/html5/simple.html

I currently use the [DT package](https://rstudio.github.io/DT/) for a shiny app, and I would like to move to gt as it is much easier to use. However, I would need those export buttons.

Thanks in advance!

**Comment by rich-iannone** [comment]
This is something that is planned. A rough design for this is described in https://github.com/rstudio/gt/issues/27. There is some initial work in this branch: https://github.com/rstudio/gt/tree/gtprex.

What we'd ultimately want to have is an easy way to have both the data and the code used to make the **gt** output table available to download.

Since this has much in common with the earlier issue, I'm going to copy in your comment to that issue and close this one.
