### ISSUE TITLE
Wrong stub width with `row_group_as_column = TRUE`

### ISSUE THREAD

**Issue by olivroy** [rstudio/gt#1799]
From the visual tests,

https://github.com/olivroy/gt/blob/borderless/pkgdown/assets/gt-latex.pdf

````qmd
---
title: title
format: pdf
---

```{r}
tab <- pizzaplace %>%
  dplyr::filter(type %in% c("classic", "veggie")) %>%
  dplyr::group_by(type, size) %>%
  dplyr::summarize(
    sold = dplyr::n(),
    income = sum(price),
    .groups = "drop"
  ) %>%
  gt(rowname_col = "size", groupname_col = "type") %>%
  tab_header(title = "Complete output") %>%
  fmt_integer(columns = sold) %>%
  fmt_currency(columns = income) %>%
  summary_rows(
    fns = list(label = "All Sizes", fn = "sum"),
    side = c("top"),
    fmt = list(
      ~ fmt_integer(., columns = sold),
      ~ fmt_currency(., columns = income)
    )
  ) %>%
  tab_options(
    summary_row.background.color = "gray95",
    row_group.as_column = TRUE
  ) %>%
  tab_stub_indent(
    rows = everything(),
    indent = 2
  ) %>%
  grand_summary_rows(
    columns = c("sold", "income"),
    fns = list(Sum ~ sum(.)),
    fmt = ~ fmt_number(.)
  ) %>%
  tab_caption("Here be caption text") %>%
  tab_spanner(
    label = "Spanner",
    columns = c("sold", "income")
  ) %>%
  tab_stubhead("Stubhead label") %>%
  tab_source_note("Source: the pizzaria") %>%
  tab_footnote("Pineapples not included")
tab
```
````

**Comment by kbrevoort** [comment]
@olivroy I took a look at this tonight, and I don't think the issue is with tab_stub_indent.  It's because Latex adds space when a table's natural width is shorter than the user-specified width.  

The change to add a floating-point environment seems to require that tables either use the entire page width unless the user specifies a width (that's something we should change, IMO).  There's no specified table width in your MWE, so Latex is stretching the table, which has undesirable results.  

We cannot change that behavior. However, if the user explicitly sets column widths, that should fix the problem. For example, adding the following additional command to your MWE should produce the output you're expecting.

```
cols_width(tab, 
                   type ~ pct(30),
                   size ~ pct(20),
                   sold ~ pct(25),
                   income ~ pct(25))
```
Let me know if that doesn't address your concerns or if I've missed something.   Thanks for pointing this behavior out!
