### ISSUE TITLE
tab_style for summary row labels

### ISSUE THREAD

**Issue by steveputman** [rstudio/gt#473]
Is there a way to target the label in the stub for styling in a summary row? It seems like the expected behavior when applying a style to a summary row (at least when `columns = TRUE`) would be to include the label in the stub. 

And you can't seem to target it with `cells_stub` by the aggregator label, which results in the not-very-surprising error `Can't bind data because some arguments have the same name`.

Thanks!

**Comment by rich-iannone** [comment]
Thanks for bringing this up. Unfortunately, this is the only location that currently can't be accessed by a `cells_*()` function, which is a shame because these labels are likely prime targets for footnotes and styling.

Also, given that this is the last location that can't be targeted, it blocks work on #176 (creating a `cells_all()` function).

To solve this, there are a few options I can think of here:

1. add `cells_stub_summary()`
2. augment `cells_stub()`
3. augment `cells_summary()`

To me, the first seems like the best option so as to not clutter the interfaces of the existing `cells_*()` functions.

**Comment by 11rchitwood** [comment]
I agree that `cells_stub_summary()` is the way to go here. Feels consistent with the rest of the API. Is `cells_stub_grand_summary() needed also? This would be useful for bolding a grand total row. Example: ![image](https://user-images.githubusercontent.com/26073857/79333822-2cab6380-7eed-11ea-9e0f-3b46f5b0100e.png)

**Comment by kendonB** [comment]
I believe this one also prevents the user from being able to change the font table wide? @rich-iannone  If so, surely this one should be labelled as a bug.
