### ISSUE TITLE
indexing in cells_data()

### ISSUE THREAD

**Issue by davebraze** [rstudio/gt#482]
R uses row major indexing.

Named arguments for cells_data(columns = NULL, rows = NULL) are defined to occur in the reverse order one would expect. Maybe not a big problem if spelling out the argument names in a call to that function. But if you are shorthanding it and passing in bare arguments, you have to remember that the first arg is col and the second row, contrary to all other indexing in R. 

This makes writing and reading code with cells_data() much more error prone than it needs to be.

A simple solution is to reverse the order of arguments in the function definition, recognizing that this will break existing code where bare arguments are passed to cells_data().

**Comment by rich-iannone** [comment]
We went with columns first and rows second because the reasoning was that formatting entire columns would be the dominant activity (where a subsection of rows is considered a tweak, and less common). I'm against changing this now and I'd actually encourage the use of the argument names for at least these two.
