### ISSUE TITLE
Create gt_tbl object from html or latex table

### ISSUE THREAD

**Issue by bbjonz** [rstudio/gt#695]
Hi,

Love the gt package and am pleased that the caption command lets it play nicely with bookdown.  I have some tables generated as either html or latex from some other packages, for example semTable.  The problem is that, as far as I can tell, gt doesn't work with either type of input.  Here's an example using a CFA from lavaan:

`
HS.model <- " visual  =~ x1 + x2 + x3 
              textual =~ x4 + x5 + x6
              speed   =~ x7 + x8 + x9 "
 
  fit <- cfa(HS.model, data=HolzingerSwineford1939)
`

I can use semTable to generate a nicely formatted CFA table in either html or latex, and I can pipe the html version to the html() function in gt, which works fine:

`
  semTable::semTable(fit, print.results = F, type = "html") %>% 
    html()
`

The problem is that I can use any of the gt formatting functions (e.g., adding a caption) on the table because the object (labelled "fit") isn't recognized as a gt_tbl object.  I've tried some messy converting of html to data tables (e.g., rvest) but the results aren't satisifying.  So, is there anyway to take html table syntax as input to creat a gt_tbl object?  Thanks in advance.

**Comment by rich-iannone** [comment]
While this would be an incredible feature of gt, I can’t imagine it would become a part of it for several reasons. Anything but the simplest HTML or LaTeX table would be incredible difficult to parse and would probably lead to disappointing results.

I think pure Markdown tables or Pandoc tables would work better for this sort of thing (since their feature sets are more constrained) but all bets are off for HTML or LaTeX conversion to gt table objects. 

Something that might work is to convince other package authors to use gt to generate tables and provide a way to return the gt table object. That sort of thing may become easier once gt gets better but their are already some packages doing this.
