### ISSUE TITLE
Relax test on unique `tab_spanner` label 

### ISSUE THREAD

**Issue by vincentarelbundock** [rstudio/gt#934]
I love the new unlimited spanner function. However, when I try to create multiple spanners with the same name, I run into this error:

``` r
library(gt)

dat <- mtcars[1:4, 1:6]

gt(dat) |>
    tab_spanner(label = "a", columns = 1:2) |>
    tab_spanner(label = "b", columns = 3:4) |>
    tab_spanner(label = "a", columns = 5:6)
#> Error: The spanner `id` provided (`"a"`) is not unique:
#> * The `id` must be unique across existing spanners
#> * Provide a unique ID value for this spanner
```

This occurs when:

1.  Two spanners have the same label on the *same* level.
2.  Two spanners have the same label on *different* levels.

It would be useful to relax this input check to allow duplicate labels. Here is a screenshot use-case which – I believe – is very common when reporting descriptive statistics or “nested” cross tabs. Note that the 3, 4, 5 labels are duplicated.

![gt](https://user-images.githubusercontent.com/987057/165086878-c78e370e-4333-41a8-a9d2-e71d89891a24.png)

**Comment by rich-iannone** [comment]
To get around this, you can provide different `id` values in the `tab_spanner()` statements. It just so happens that the `id` value, by default, is the same as the `label`. 

We need to have different id values for different spanners in order to be able to precisely target the different cells during styling or applying footnotes.

**Comment by vincentarelbundock** [comment]
Thanks a lot, this solves it.

Sorry for raising an already-solved problem.
