### ISSUE TITLE
as_rtf example could not run

### ISSUE THREAD

**Issue by elong0527** [rstudio/gt#98]
The example code of `as_rtf` could not run, because the function `migrate_unformatted_to_output` did not have a default value for `context` 

https://github.com/rstudio/gt/blob/bc1a5f4f44b268b19c916936f69c6b0edadeec77/R/as_rtf.R#L94

**Comment by rich-iannone** [comment]
Thanks for posting this issue. This will be the next thing that gets fixed for sure. It's a known problem but one that we are keen to address.

**Comment by elong0527** [comment]
Thanks Richard! Tareef showed the powerful `gt` package to us when he visited Merck last week. 

It is a wonderful idea to create the `gt` class, so we can focus on create a render function to adjust industry/company standard. 

RTF format is still heavily used in clinical trial reports (even through I am in favor of html reports), It would be very nice to have a powerful RTF engine within R+gt to handle items below (so one can make argument of using R for regulatory works). 

1. column width in `gt` class. (it is a feature clinical programmer heavily used to creat RTF table)
2. repeat header indicator in `gt` class (So `as_rtf` can indicate if we need to repeat header in the document. similar idea in kableExtra https://github.com/haozhu233/kableExtra/issues/13)
3. concatenate `gt` tables in RTF table  
         Sometimes, it is required to create a table by concatenate two small tables together, RTF is simple to handle this as RTF format table by row. that would be wonderful if `as_rtf` could have an option to not render RTF header, then we can combine the multiple raw RTF table together.  
4.  table border and cell format 
     My initial thoughts must be naive, however `as_rtf` will be very powerful if it can understand the border format such as the example below. So programmer can customize the border format like below.  The similar idea could apply to table margin, outside title/subtitle, data source etc.  

```
row_boarder <- list(
'\\trbrdrt\\brdrdb\\brdrw15\\trbrdrl\\brdrs\\brdrw15\\trbrdrb\\brdrdb\\brdrw15\\trbrdrr\\brdrs\\brdrw15',
  '\\clbrdrt\\brdrdb\\brdrw15\\clbrdrl\\brdrs\\brdrw15\\clbrdrr\\brdrhair\\cellx1767',
  '\\clbrdrt\\brdrdb\\brdrw15\\clbrdrb\\brdrhair\\clbrdrr\brdrs\\brdrw15\\cellx3403',
  end = ''
)
```

Some of the features may already built in `gt`, I just make a note based on the use case in clinical trial report with RTF format for your reference.

**Comment by rich-iannone** [comment]
I'd love to have all of those features you cited implemented in **gt**, I'll create separate issues for each of the items to better track their development. The use case of RTF for pharma was a big consideration for implementing RTF output in general, so I'm happy to be getting feedback and design direction from you.

If you'd like to provide some further example outputs, that would be great because we could have some targets to shoot for (I'll put them in separate issues, and prioritize them). Also, if you or a colleague would like to take on a more active role in submitting code for RTF, that would be a great option to speed up RTF output development as well.
